# try...catch语句

在这一节中，我们将认识三个新的关键字：`try` `catch` `finally`。

假设我们有一个用于搜索数据库的函数

```js
/**
 * 数据库中的信息:
 * hello -> world
 * 123 -> 456
 * asdf -> ghjk
 * qwer -> ty
 * git -> hub
 */

function searchDB(keyword) {
    // ...
}

searchDB("hello"); // "world"
searchDB("qwer"); // "ty"
searchDB("git"); // "hub"
searchDB("baidu"); // (报错：找不到值)
```

这个函数输入一个关键字(keyword)，然后输出在数据库中搜索到的值。但是，当函数无法通过这个关键字从数据库中搜索到相应的值，那么就会报错，而我们又无法保证程序的使用者输入的值每次都能搜索得到，那么怎么办呢？

这时候，我们就可以通过try...catch来捕捉这个报错，然后弹出提示框来提醒用户“找不到这个值”。

```js
try {
    searchDB("abc");
} catch {
    alert("找不到值!");
}
```

如果我们还需要获取更具体的错误的信息，那么就可以这么写：

```js
try {
    searchDB("abc");
} catch (err) {
    alert("找不到值! 错误信息："+ err);
}
```

而如果我们还要再加一段无论是否报错都会执行的代码，就可以再加一句`finally`：

```js
try {
    searchDB("abc");
} catch (err) {
    alert("找不到值! 错误信息："+ err);
} finally {
    // ... (要执行的语句)
}
```

或者直接把代码写在后面：

```js
try {
    searchDB("abc");
} catch (err) {
    alert("找不到值! 错误信息："+ err);
}

// ... (要执行的语句)
```
